apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-stock-future-ingress-test
  namespace: web-stock-future-test
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - api-test-iprime.nefyo.com
        - test-iprime.nefyo.com
      secretName: web-stock-future-cert-secret
  rules:
    - host: api-test-iprime.nefyo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-stock-future-backend-service-test
                port:
                  number: 7100
    - host: test-iprime.nefyo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-stock-future-frontend-service-test
                port:
                  number: 7201
